name: "Deploy WebApi to IIS"
author: "felix"
branding:
  icon: upload-cloud
  color: blue

inputs:
  app_name:
    description: "IIS App name"
    required: true
  app_pool_name:
    description: "Application Pool Name"
    required: true
  app_pool_username:
    description: "Application Pool UserName"
    required: true
  app_pool_password:
    description: "Application Pool Password"
    required: true
  physical_path:
    description: "The path to the source directory that will be deployed"
    required: true
  virtual_path:
    required: true
  website_name:
    description: "IIS website name"
    required: true
  package_path:
    description: "File path to the package or a folder"
    required: true
  dotnet_version:
    required: false
    default: 'v4.0'
runs:
  using: "composite"
  steps:
    - name: Deploy Web Application
      shell: powershell
      run: >
        ${{ github.action_path }}/scripts/deploy-webapplication.ps1
        -app_name: ${{ inputs.app_name }} 
        -app_pool_name: ${{ inputs.app_pool_name }} 
        -app_pool_username: ${{ inputs.app_pool_username }} 
        -app_pool_password: ${{ inputs.app_pool_password }} 
        -physical_path: ${{ inputs.physical_path }} 
        -virtual_path: ${{ inputs.virtual_path }} 
        -website_name: ${{ inputs.website_name }} 
        -package_path: ${{ inputs.package_path }} 
        -dotnet_version: ${{ inputs.dotnet_version }} 